### ISSUE TITLE
Problems with sound and video (with impress-audio.js)

### ISSUE THREAD

**Issue by Kuhlig** [impress/impress.js#867]
Hello

I have the following problems if someone could help me would be very nice. It only  must work with Chrome, Firefox and others we (I) can do later.

1) The video in the first slide does not start automatically. it used to work at the moment I don't know why it doesn't work anymore or onyl sometimes.

2) When the video starts automatically, the sound of the second slide is also played on the first slide and then on the second slide again

3) The console shows the following error 
impress-audio.js:36 Uncaught TypeError: $el.parent is not a function
    at impressObj.goto (impress-audio.js:36:20)
    at impress.js:4478:17
    at impress.js:1240:24

The link to the page would be 
User: help
Passwd: ThankYou

[Link to video error](https://sampleset.ico-cert.net/ExamSet/slide/en/dca83f88-ba05-4082-9502-22faac8a629c/880e20e6-64a9-4a8e-87d3-553a04cc70a1/ICO+ISMS+27001%3A2022+Foundation#/start)

ThankYou Rob

PS the content is created from a DB . generating it may take a while

**Comment by simplePCBuilding** [comment]
Hello
Sorry for the late response, I currently have barely any time to work on projects other than a few select ones.

Have you tried using older versions of impress.js as well? I will add this to my ToDo list for beginning of December and I will look into this.

**Comment by simplePCBuilding** [comment]
@Kuhlig 

Is impress-audio.js even an officially supported plugin? Because I don't recall ever seeing any code in this or the extras repositories. After a quick search I've found this: https://github.com/danielsimons1/impress-audio

Is this the thing you've been using?

On another note, I'll think about creating an official plugin for this with the refactor as well, so any suggestions would be highly appreciated.

**Comment by Kuhlig** [comment]
I was using this one ... https://github.com/danielsimons1/impress-audio ... thanks for your help curob

**Comment by henrikingo** [comment]
Hi

Unfortunately I didn't get past the password prompt

**Comment by simplePCBuilding** [comment]
@Kuhlig We can't get past the pw prompt. Can you fix this please?
